const fs = require("fs");
const path = require("path");
const archiver = require("archiver");

const root = path.resolve(__dirname, "..");
const siteDir = path.join(root, "site");
const extensionDir = path.join(root, "extenstion");
const publicDir = path.join(root, "public");
const publicAssetsDir = path.join(publicDir, "assets");
const downloadsDir = path.join(publicDir, "downloads");
const zipPath = path.join(downloadsDir, "randy-the-otter-extension.zip");

function parseEnvValue(content, key) {
  const re = new RegExp(`^\\s*${key}\\s*=\\s*(.*)\\s*$`, "m");
  const m = content.match(re);
  if (!m) return null;
  let v = m[1].trim();
  // strip surrounding quotes
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
    v = v.slice(1, -1);
  }
  return v;
}

function getBackendUrl() {
  // Prefer process.env (CI/production), fallback to .env file at repo root
  let url = process.env.BACKEND_CLOUD_URL;
  if (url === undefined || url === null || String(url).trim() === "") {
    // try .env file
    const envPath = path.join(root, ".env");
    if (fs.existsSync(envPath)) {
      try {
        const content = fs.readFileSync(envPath, "utf-8");
        const parsed = parseEnvValue(content, "BACKEND_CLOUD_URL");
        if (parsed !== null) url = parsed;
      } catch (_) {}
    }
    // also try .env.example as last resort (should be empty by default)
    if ((url === undefined || url === null || String(url).trim() === "") ) {
      const examplePath = path.join(root, ".env.example");
      if (fs.existsSync(examplePath)) {
        try {
          const content = fs.readFileSync(examplePath, "utf-8");
          const parsed = parseEnvValue(content, "BACKEND_CLOUD_URL");
          // only use example if it is non-empty (avoid overriding empty default)
          if (parsed && parsed.trim()) url = parsed;
        } catch (_) {}
      }
    }
  }
  if (typeof url !== "string") return null;
  url = url.trim();
  if (!url) return null;
  // strip trailing slashes
  url = url.replace(/\/+$/, "");
  return url || null;
}

function injectBackendConfig() {
  const backendUrl = getBackendUrl();
  const configPath = path.join(extensionDir, "src", "config.js");
  const fallback = "http://127.0.0.1:5000";
  const finalUrl = backendUrl || fallback;
  const content = `// Auto-generated by scripts/build-site.js from BACKEND_CLOUD_URL env var.\n// Do not edit manually — set BACKEND_CLOUD_URL in .env and rebuild.\n// Falls back to localhost for local dev.\nvar BACKEND_URL = "${finalUrl.replace(/"/g, '\\"')}";\n`;
  fs.writeFileSync(configPath, content, "utf-8");
  if (backendUrl) {
    console.log(`Injected BACKEND_URL = ${finalUrl} into extenstion/src/config.js`);
  } else {
    console.log(`BACKEND_CLOUD_URL not set — using fallback ${fallback} for extenstion/src/config.js`);
  }
  return finalUrl;
}

function removeIfExists(target) {
  fs.rmSync(target, { recursive: true, force: true });
}

function copyDirectory(source, destination) {
  fs.cpSync(source, destination, { recursive: true });
}

function createExtensionZip() {
  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(zipPath);
    const archive = archiver("zip", { zlib: { level: 9 } });

    output.on("close", () => {
      console.log(`Created ${path.relative(root, zipPath)} (${archive.pointer()} bytes)`);
      resolve();
    });
    archive.on("error", reject);
    archive.pipe(output);
    archive.directory(extensionDir, false);
    archive.finalize();
  });
}

async function build() {
  injectBackendConfig();
  removeIfExists(publicDir);
  fs.mkdirSync(publicAssetsDir, { recursive: true });
  fs.mkdirSync(downloadsDir, { recursive: true });
  copyDirectory(siteDir, publicDir);
  copyDirectory(path.join(extensionDir, "src", "assets"), publicAssetsDir);
  await createExtensionZip();
}

build().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
