// Auto-generated by scripts/build-site.js from BACKEND_CLOUD_URL env var.
// Do not edit manually — set BACKEND_CLOUD_URL in .env and rebuild.
// Falls back to localhost for local dev.
var BACKEND_URL = "http://127.0.0.1:5000"